### ISSUE TITLE
"cached" ion-views showing up over "active" ion-views when going back

### ISSUE THREAD

**Issue by dts** [driftyco/ionic-service-deploy#11]
If I have a navigation stack deeper than 2 (i.e. base, middle, top, or more), and I go "back", reductin gthis stack to 2, the cached view that is the base is visible, although transparent, over the main view I should be looking at.  This only occurs when I push my app via Deploy, and only occurs when loading the updated app (not when the exact same code is being run un-deployed).  It happens 100% reliably in both simulator and real devices, but never in browsers.  An image is attached of what it looks like.  I can inspect and see that erroneous styles and attributes are set on the ion-view.

I've spent a while trying to figure out what's going on, and I'd be happy to attempt to re-create this effect from scratch, but I'd rather not go to the trouble if someone else has seen something like this and it's something silly I've done.

![img_2062](https://cloud.githubusercontent.com/assets/273856/7976346/be056166-0a2e-11e5-8364-0dc9ec808567.jpg)

**Comment by ericb** [comment]
@dts Are you able to provide a minimal code example to replicate with?

**Comment by dts** [comment]
I will try to put something together that demonstrates this effect reliably.

**Comment by ericb** [comment]
@dts Thanks!

**Comment by dts** [comment]
So far no luck in reproducing it, but I did isolate the code that is causing the problem on my end.  On launch, I perform a quick net check to see if the current user's API token is still valid (in case they have logged out, or canceled their account, etc).  During this net check I was diverting to a temporary landing page.  Once the check is over, I forward them to the route they originally requested.  This re-routing during start-up, in combination with the deploy mechanism, appears to cause something to get screwed up in the view tree.  It appears there are a large combination of factors required to make this happen, but I can easily remove one of those pieces from my app that will fix the issue from my perspective.

I will continue to fool around with the stripped-down model, but now that I can pretty solidly identify the issue in my own code, it is no longer a priority.

**Comment by Ionitron** [comment]
Greetings @dts!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
