### ISSUE TITLE
Include standalone version of ionic.Platform to avoid loading all of ionic code first

### ISSUE THREAD

**Issue by jskrzypek** [driftyco/ionic-service-deploy#13]
This module (as well as [`ionic-service-core`](https://github.com/driftyco/ionic-service-deploy)) depends on [`ionic`](https://github.com/driftyco/ionic) to be completely loaded, just to use `ionic.Platform.isAndroid()`. Perhaps it would be easier to just include a standalone function, such as the userAgent hack in [js/utils/platform.js line 320](https://github.com/driftyco/ionic/blob/master/js/utils/platform.js#L320)? I'll attach a PR soon.

**Comment by jskrzypek** [comment]
I just realized that you provide a function that does this check already in `$ionicApp` from [`ionic-service-core`](https://github.com/driftyco/ionic-service-core/blob/master/ionic-core.js#L223-225) so I'll use that instead of `ionic.Platform.isAndroid()` in the PR.

**Comment by ericb** [comment]
This was actually addressed with the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client)

**Comment by jskrzypek** [comment]
Yup I've been looking at this over the past day. It looks like it addresses the problem nicely :+1:
