### ISSUE TITLE
Didnt delete not used versions files

### ISSUE THREAD

**Issue by alamops** [driftyco/ionic-service-deploy#16]
For each update, increase my app size, without I create new files.
There is a way to delete not used versions files?

**Comment by ericb** [comment]
@alamops Right now there is no way to delete them directly, but I did have plans to add more support around the local versions. I will update with more info as it becomes available.

**Comment by jfitz0** [comment]
It would be nice if it automatically delete old versions from the phone (or you could configure it to do so)

**Comment by TombolaShepless** [comment]
+1 This is the reason we cannot start using the deploy service right now. @ericb any word on this mate?

**Comment by TombolaShepless** [comment]
@ericb Sorry to pester, but is there any word on this issue?

**Comment by ericb** [comment]
@TombolaShepless Sorry! I must have missed your original comment. So this will definitely be addressed, but I don't have a timeline for you at the moment. We're gearing up to release some updates to the service clients (including deploys). Once that happens I should be able to swing around to this issue.

**Comment by akships** [comment]
+1 any updates on this ?

**Comment by ericb** [comment]
@kcedric This is an outdated and unsupported library. Please check out the [cloud-client](https://github.com/driftyco/ionic-cloud) and our latest [docs](http://docs.ionic.io) for more information.
