### ISSUE TITLE
Problem cordova.js?Cache ..

### ISSUE THREAD

**Issue by brunoksato** [driftyco/ionic-service-deploy#17]
Problem with reference path, not found cordova.js why have cordova.js?Cache.. in name file, more show console.log IonicDeploy init

Solution ? My error ?

**Comment by ericb** [comment]
@brunoksato You need to remove the cordova.js reference in your index.html. `ionic-service-core` now bootstraps the cordova.js file for you.

**Comment by brunoksato** [comment]
Ok, Thanks !
