### ISSUE TITLE
Consider supporting metadata about versions

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-service-deploy#20]
Right now you get a boolean saying if an update is available, but it may be nice if we could include metadata about an update. Imagine a JSON packet with strings like "required:true" and "changes:More cowbell". The client code could then use this data however it wants to. So maybe I want to use a "required" flag to let users decide if they want to update. Maybe I use "changes" so I can tell the user what the update is. The idea is that I may want to do more than just say an update is available.

This should be totally optional of course.

**Comment by bymodude** [comment]
I was just looking for this functionality, adding my vote for this enhancement!

**Comment by ericb** [comment]
:+1:  For the update message. I will try to lump this in with some other updates I'm currently working on.

**Comment by petrvojta** [comment]
+1

**Comment by bymodude** [comment]
im trying to deploy updates with two behaviours: 

1) critical updates: as soon as ionic deploy has extracted the update the user is shown an alert with just an OK button and app will restart (and start to use the updated code) immediately after pressing OK. 

2) non-critical updates: ionic deploy extracts the update, app doesnt do anything special, when user restarts the app it will use the new code

having some meta-data capability as pointed out in this issue would enable this scenario.

**Comment by dotlouis** [comment]
There is a method [`$ionicDeploy.info()`](http://docs.ionic.io/docs/deploy-usage#section-getting-deploy-info) that gives some data but very few; two actually:
- the binary version
- the deploy uuid

However there is no way to know the active deploy build number the app is running _(deploy uuid says "NO_DEPLOY_AVAILABLE")_

Also, as mentionned by @cfjedimaster it would be useful to be able to get the **note** property of ionic.io 's dashboard.
A way to pass additionnal payload metadata would be the cherry on top.

**Comment by ericb** [comment]
@dot-louis deploy uuid will give you the current uuid, but will get that message if you've just run a build on your device as we block the current deploy when a device binary is updated (this is intentional, so that you can continue to develop your app while deploy is active). If you want to see this in action you can deploy a new update to the device after you've run a new build on your device/emulator.

**Comment by dotlouis** [comment]
@ericb Oh, my bad I couldn't figure out how to get that number.
May I ask how do you detect if I've just run a build on the device ?

**Comment by ericb** [comment]
@dot-louis There is a version label generated for both [android](https://github.com/driftyco/ionic-plugin-deploy/blob/master/src/android/IonicDeploy.java#L119-L123) and [ios](https://github.com/driftyco/ionic-plugin-deploy/blob/master/src/ios/IonicDeploy.m#L60-L72) that we then check against.
