### ISSUE TITLE
Commenting out cordova.js

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-service-deploy#21]
Only the docs for Deploy tell you to comment out cordova.js, but the docs say:

"as well as comment out cordova.js, which is automatically bootstrapped by the ionic-service-core:"

that seems to imply anything using Services will need this change to, but as far as I know, Push and Analytics don't require this.

**Comment by ericb** [comment]
Correct. Service Core will run the bootstrap, but only deploy has a direct dependency on removing cordova.js (due to the way cordova compiles the cordova_plugins.js with relative paths). 

We're going to be launching something soon that will remove the need to manually do this.

**Comment by ghost** [comment]
I integrate it the deploy mods to my app. It works fine with iOS, but it does not work with Android:
ionic run android -l --device
...
Installing app on device...

/Users/herve76/Desktop/JSapp/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
ERROR: Failed to launch application on device: ERROR: Failed to install apk to device:  pkg: /data/local/tmp/android-debug.apk
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE]

Is it supposed to be working?

Cordially,

H

**Comment by ghost** [comment]
Now working after removing the app from the phone.

**Comment by cfjedimaster** [comment]
So to be clear, we no longer comment it out?

**Comment by ericb** [comment]
You can always comment it out if your'e using `ionic-service-core` (but it's not required), but you _have_ to comment it out if you're using `ionic-service-deploy`

**Comment by cfjedimaster** [comment]
I'd say this bug should be re-opened then. I think the docs should add a bit more information about why this is done, and being extra clear that it is ONLY required for Deploy. Or - even better - I'd be consistent and always comment it out. It may not be necessary for Push/Analytics, but it would be - well consistent. ;)
