### ISSUE TITLE
Broken after first deploy update

### ISSUE THREAD

**Issue by jfitz0** [driftyco/ionic-service-deploy#23]
I had ionic deploy working perfecting on Android until two days ago when I updated to Android 5.0 on my phone (may or may not be related). Now even when using the simplest implementation (exactly as it is from the instructions http://docs.ionic.io/v1.0/docs/deploy-from-scratch) after it performs the first update it is not able to find the new index file and the app fails to open.

ERR_FILE_NOT_FOUND file:///data/data/com.xxxxxxxxxx

Attached screenshot from the console inspector:
![image](https://cloud.githubusercontent.com/assets/3335658/8296691/2335dfee-1997-11e5-815e-35314929572a.png)

Phone: Samsung S5
Android Version: 5.00
Please let me know what else I can include to provide more diagnostically relevant information. 

Controller Code (copied exactly as is from tutorial):

``` javascript
.controller('DashCtrl', function($scope, $ionicDeploy) {
  // Update app code with new release from Ionic Deploy
  $scope.doUpdate = function() {
    $ionicDeploy.update().then(function(res) {
      console.log('Ionic Deploy: Update Success! ', res);
    }, function(err) {
      console.log('Ionic Deploy: Update error! ', err);
    }, function(prog) {
      console.log('Ionic Deploy: Progress... ', prog);
    });
  };

  // Check Ionic Deploy for new code
  $scope.checkForUpdates = function() {
    console.log('Ionic Deploy: Checking for updates');
    $ionicDeploy.check().then(function(hasUpdate) {
      console.log('Ionic Deploy: Update available: ' + hasUpdate);
      $scope.hasUpdate = hasUpdate;
    }, function(err) {
      console.error('Ionic Deploy: Unable to check for updates', err);
    });
  }
})
```

**Comment by bymodude** [comment]
I'm having the same problem, on Android 4.4.2, after download of update and $ionicDeploy.load(); I get the same ERR_FILE_NOT_FOUND file:///data/data/com.xxxxxxxxxx error.

I tried the full manual mode from here: http://docs.ionic.io/v1.0/docs/deploy-updating-apps
and extraction progress only returns 0, and no other progress before the $ionicDeploy.load() is kicked off

**Comment by ericb** [comment]
Hey guys, we are aware of this issue, it's an issue with the CLI. You can track the progress with driftyco/ionic-cli/issues/494

As a temporary solution, you can downgrade your CLI to 1.5.0 `npm install -g ionic@1.5.0`

**Comment by ericb** [comment]
Please follow the discussion on driftyco/ionic-plugins-deploy#12
