### ISSUE TITLE
$ionicDepoly.download is not working

### ISSUE THREAD

**Issue by johnpeace20** [driftyco/ionic-service-deploy#24]
$ionicDeploy.check();
This function is working fine, but download function is not working.

Here is my code.
$ionicDeploy.download().then(function() {
      // Extract the updates
      $ionicDeploy.extract().then(function() {
        // Load the updated version
        $ionicDeploy.load();
      }, function(error) {
        // Error extracting
        alert(error);
![log](https://cloud.githubusercontent.com/assets/10144534/8349957/cad1a568-1b53-11e5-8044-45dfc2e46241.jpg)

      }, function(progress) {
        // Do something with the zip extraction progress
        //$scope.extraction_progress = progress;
       alert(progress)
      });
    }, function(error) {
      // Error downloading the updates
      alert(error);
    }, function(progress) {
      alert(progress);
    });

Even I can't see any error alerts.
I tracked log, but no error logs too.

I attached last part of log as image.
Any helps would be great.
Thanks.

**Comment by ericb** [comment]
Have you deployed a version yet?

**Comment by johnpeace20** [comment]
Thanks for your response.

Yes. I did it.
I tried to deploy it several times and now its working. Don't know why it didn't worked at the moment.
By the way, I noticed I can't use this function here in China.
Is there any solution for us?

**Comment by ericb** [comment]
I'm confused, you're saying it's working now, but you can't use it in China?
