### ISSUE TITLE
Ionic Deploy Plugin Error on Android 4.3 or older

### ISSUE THREAD

**Issue by MikeLallemont** [driftyco/ionic-service-deploy#27]
When running our app on Android devices we receive this error:

java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

**Comment by ericb** [comment]
What version of Android?

**Comment by ericb** [comment]
Nevermind, i didn't see it in the title initially. :)

**Comment by ericb** [comment]
This is a duplicate of driftyco/ionic-plugins-deploy/issues/19. Please follow that issue for updates.
