### ISSUE TITLE
deploy 1 app but load diffrente html, css, js depending on customer login

### ISSUE THREAD

**Issue by pablomaurer** [driftyco/ionic-service-deploy#3]
Hi, 

I'm making a b2b app for our customers. But depending on the Company we build it for, they may need small custom changes to fit the workflow of their company..

Instead of publishing multiple apps in the appstore for each company, it would be nice to have the posibility to decide which html, css, js files to load depening on the login, app-id or something like that..

Thanks alot!

**Comment by jskrzypek** [comment]
I expect you can probably accomplish that with different app_ids in your config of the $ionicAppProvider

**Comment by arieljake** [comment]
Yes! thank you @jskrzypek...this would allow us to do A/B testing using Deploy.

**Comment by ericb** [comment]
This is now possible with [Deploy Channels](http://docs.ionic.io/docs/deploy-channels).

**Comment by arieljake** [comment]
Great! :)
