### ISSUE TITLE
cordova.plugins are not loaded after update()

### ISSUE THREAD

**Issue by aromka** [driftyco/ionic-service-deploy#31]
After running update() and app reloads, plugins don't work anymore:

`$ionicDeploy: Unable to check for Ionic Deploy updates Plugin not loaded`

`TypeError: undefined is not an object (evaluating 'cordova.plugins.Keyboard')`

**Comment by ericb** [comment]
Do you have a reference to cordova.js in your index.html? If so you'll need to remove it.

**Comment by aromka** [comment]
yup, that was it. thanks!
