### ISSUE TITLE
Clarify docs on testing Ionic deploy

### ISSUE THREAD

**Issue by mkolodny** [driftyco/ionic-service-deploy#32]
In the Testing Ionic Deploy section of the [Ionic deploy](http://docs.ionic.io/docs/deploy-from-scratch) docs, it says:

> Be careful not to deploy versions of your app which use older versions of the components, as you may lose access to your cordova native plugins.

Which "components" are the docs referring to?

This is a pretty important clarification considering that not following these directions means that you "may lose access to your cordova native plugins".

**Comment by ericb** [comment]
Added a slightly different text with a link to binary versioning, basically this is a warning that if you were to upload an app using a specific version of the core/deploy service modules, and then later try to deploy that version when your device was already running much newer versions with a newer deploy plugin, it's possible you could update into a now broken state.

This is why we recommend you test all deploys in a testing channel before releasing to a production channel.
