### ISSUE TITLE
TypeError: Cannot read property 'onReady' of null

### ISSUE THREAD

**Issue by egoossens** [driftyco/ionic-service-deploy#34]
I get this error both when injecting $ionicDeploy or when running new Ionic.Deploy().
It seems Ionic.IO.main is null.

What did I miss?

Thanks and keep up the good work!

**Comment by ericb** [comment]
@egoossens Sorry I need to update the README for all these components, everything is now bundled in the [ionic-platform-web-client](https://github.com/driftyco/ionic-platform-web-client). You'll need to remove the older components and make sure to run `Ionic.io();` somewhere prior to using any service functionality.

I plan to remove the need to call `Ionic.io` soon.
