### ISSUE TITLE
null error in ionic.io.bundle.min.js

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-service-deploy#35]
I'm getting this error in a new app I just made that uses check():

[Error] TypeError: null is not an object (evaluating 'u.IonicPlatform.getMain().onReady')
    e (ionic.io.bundle.min.js, line 2)
    (anonymous function) (app.js, line 21)
    (anonymous function) (ionic.bundle.js, line 48811)
    onPlatformReady (ionic.bundle.js, line 2447)
    onWindowLoad (ionic.bundle.js, line 2428)

**Comment by ericb** [comment]
This is most likely caused by a missing call to `Ionic.io();`, I am removing the need to call taht manually in the next update to the platform client..
