### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by okonon** [driftyco/ionic-service-deploy#8]
Hello, 
after installing deploy service and its required plugin i am getting following errors in safari console after successful first run.
- platform iOS
  ionic info:

```

```

errors from safari console:

```
file:///Users/me/Library/Developer/CoreSimulator/Devices/FC644025-A88A-4C11-AA05-BFE0A0FC83CE/data/Containers/Data/Application/6D3751F9-E91C-4492-9BE2-D671884392FF/Documents/f25a02ac009a11e5b6b1be7a94d59180/cordova.js?ionicCachebuster=90660
[Error] Failed to load resource: The requested URL was not found on this server. (cordova.js, line 0)
```

it seems that the app does not load `cordova.js` anymore. Next there is another error:

```
ReferenceError: Can't find variable: cordova
```

**Comment by okonon** [comment]
Here is my update app code:

```
$ionicDeploy.check().then(function(response) {
          // response will be true/false
          log.w('*** chekcing for updates: - ' + angular.toJson(response));
          if (response) {
            // Download the updates
            $ionicDeploy.download().then(function() {
              log.w('*** downloaded update');
              // Extract the updates
              $ionicDeploy.extract().then(function() {
                log.w('*** extracted update');
                // Load the updated version
                //$ionicDeploy.load();
              }, function(error) {
                log.w('*** error extracting update: ' + angular.toJson(error));
                // Error extracting
              }, function(progress) {
                // Do something with the zip extraction progress
                log.w('*** progress of update extraction: ' + angular.toJson(progress));
                //$scope.extraction_progress = progress;
              });
            }, function(error) {
              // Error downloading the updates
            }, function(progress) {
              // Do something with the download progress
              log.w('*** progress of update download: ' + angular.toJson(progress));
              //$scope.download_progress = progress;
            });
          } else {
            // No updates, load the most up to date version of the app
            log.w('*** chekcing for updates: no update available');
            $ionicDeploy.load();
          }
        },
        function(error) {
          // Error checking for updates
          log.w('*** error chekcing for update.');
        });
```

**Comment by okonon** [comment]
I am checking for app update instead `$ionicPlatform.ready` function and not sure if this is correct. Where  do you recommend checking for updates? Outside of ionicPlatform.ready in `app.run` block?

**Comment by okonon** [comment]
I just answered my own question. You have to run this code inside ionicPlatform.ready because it relies on cordova plugin that is not available yet outside this function. Back to same issue

**Comment by okonon** [comment]
Ok, so if i switch my code to use this example from documentation using watch function:

```
$ionicDeploy.watch().then(function(){}, function(){}, function(hasUpdate) {
             // called whenever there is a new version.
             // Show a prompt to the user asking them to update or not
             // If they choose to update, call $ionicDeploy.update();
          log.w('*** update available : - ' + angular.toJson(hasUpdate));
          if(hasUpdate){
            log.w('*** updating app....');
            $ionicDeploy.update();
          }
           });
```

The app updates successfully how ever the app does not 'see' cordova.js (bunch of `ReferenceError: Can't find variable: cordova` errors).

However when i restart the app everything is fine!
 so what i am going to do is ask user for update, if answer is Yes, then update the app and close it so user will need to relaunch it

**Comment by okonon** [comment]
It turns out that `$ionicDeploy.load()` loads new version of the app and messes up cordova.js reference. So what i had to do is after successful update, do not call `$ionicDeoploy.load()' and force user to restart the app.

**Comment by jskrzypek** [comment]
Did you follow the instructions regarding loading the scripts? make sure you put this in your `index.html`

``` html
<script src="lib/ionic-service-core/ionic-core.js"></script>
<script src="lib/ionic-service-deploy/ionic-deploy.js"></script>
<!-- <script src="cordova.js"></script> -->
```

Also make sure that these are loaded before your app's code

**Comment by ericb** [comment]
As @jskrzypek said, you need to remove the cordova.js script.
Also, please make sure to update to the latest ionic-service-core, ionic-service-deploy, and ionic-plugin-deploy and do a clean rebuild (I would uninstall the app completely and start over after adding the new components) -- there has been some major changes to the deploy plugin.

**Comment by okonon** [comment]
@ericb does ionic-service-core load cordova.js?

**Comment by ericb** [comment]
@softBarbarian Yes, we bootstrap the cordova.js for you, but only if it wasn't found already, so you would need to remove the cordova.js include from your index.html

**Comment by okonon** [comment]
Thanks will do

**Comment by mahalakshme** [comment]
Hi,
I am facing the same issue after successful first update of my app(after $ionicDeploy.load()) in the latest version of ionic-plugin-deploy and ionic-platform-web-client. I am facing the above error only in iOs. In android it is working fine. I didn't include cordova.js script in my index.html file. And also during each run I uninstalled the previous app. Any ideas why I am facing the issue?

**Comment by fuhongbo** [comment]
@mahalakshme i have the same issue,do you have solution now?

**Comment by mahalakshme** [comment]
I dont know yet:(

**Comment by ashishtilara** [comment]
+1
