### ISSUE TITLE
Progress returned in update promise gives incorrect value.

### ISSUE THREAD

**Issue by jaszczur171** [driftyco/ionic-service-deploy#9]
The value returned in the progress should return a value from 0 to 100. Currently the value is calculated incorrectly.

**Comment by jskrzypek** [comment]
Does your code give correct reports? I don't think your actually changes the calculation.

**Comment by jaszczur171** [comment]
Yea it does. It returns a range from 0 to 100.

—

**Comment by jskrzypek** [comment]
:+1: 
My bad, I only looked at the code changes, and I misread that you were doing `downloadProgress = downloadProgress +(result/2)` in [line 224](https://github.com/jaszczur171/ionic-service-deploy/blob/39e7fa8350b6cbc2fa7309358bbd597ff9b42700/ionic-deploy.js#L224) before.

**Comment by jaszczur171** [comment]
No worries mate.

On Wed, Jun 3, 2015 at 11:28 AM, Joshua Skrzypek notifications@github.com
wrote:

> [image: :+1:]
> My bad, I only looked at the code changes, and I missed that you removed
> the sum with downloadProgress from line 224
> https://github.com/jaszczur171/ionic-service-deploy/blob/39e7fa8350b6cbc2fa7309358bbd597ff9b42700/ionic-deploy.js#L224
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/driftyco/ionic-service-deploy/issues/9#issuecomment-108291111
> .

## 

Kind regards

Tomasz Kandziora
Director: Lemon Moose Games Ltd

Twitter: @LemonMooseGames
Skype:  jaszczurro171
Tel: +44 (0191) 490 9323
Mobile: +44 (0) 7535 947 172
Web:   www.lemonmoosegames.com

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed. If
you are not the intended recipient you are notified that disclosing,
copying, distributing or taking any action in reliance on the contents of
this information is strictly prohibited.
E-mail sent to or from Lemon Moose Games does not automatically imply any
contractual or other legal liability.

Company Name: Lemon Moose Games Ltd
Company Registration No: 7919730
Place of Registration: England & Wales

Registered Office:   Gateshead International Business Centre, Mulgrave
Terrace, Gateshead, NE8 1AN

**Comment by ericb** [comment]
Merged the pull request and pushed into the latest 0.0.6 release. :+1:
